[package]
name = "search"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
math = { path = "../math" }
grid = { path = "../grid" }
serde = "0.9"
serde_derive = "0.9"
