[package]
name = "ecs_core"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
fnv = "1.0"

[build-dependencies]
statecs = { path = "/home/steve/src/statecs" }
