imports = [
    "ecs_core::*",
    "math::*",
    "engine_defs::*",
    "message::*",
    "content_types::*",
    "util::ScheduleTicket",
]

flags = [
    { name = 'solid' },
    { name = 'collider' },
    { name = 'destroy_on_collision' },
    { name = 'pc' },
    { name = 'floor' },
    { name = 'should_render' },
    { name = 'enemy' },
    { name = 'projectile' },
    { name = 'projectile_collider' },
    { name = 'bump_attackable' },
    { name = 'acid_animation' },
    { name = 'acid' },
    { name = 'can_run_over' },
    { name = 'can_be_run_over' },
    { name = 'bloodstain_on_death' },
    { name = 'destroy_when_stopped' },
    { name = 'destroy_when_out_of_bounds' },
    { name = 'health_bar' },
    { name = 'complex_damage' },
    { name = 'bullet' },
    { name = 'letter' },
    { name = 'explode_on_collision' },
    { name = 'explosion' },
    { name = 'destroyed_by_explosion' },
    { name = 'triggers_explosion' },
    { name = 'level_switch_auto' },
]

data = [
    { name = 'consumable_type', type = 'ConsumableType', copy = true },
    { name = 'armour_upgrade', type = 'usize', copy = true },
    { name = 'repair_type', type = 'RepairType', copy = true },
    { name = 'letter_count', type = 'usize', copy = true },
    { name = 'shooter_id', type = 'EntityId', copy = true },
    { name = 'bump_verb', type = 'VerbMessageType', copy = true },
    { name = 'bank', type = 'usize', copy = true },
    { name = 'price', type = 'usize', copy = true },
    { name = 'gun_type', type = 'GunType', copy = true },
    { name = 'gun_range', type = 'usize', copy = true },
    { name = 'current_speed', type = 'usize', copy = true },
    { name = 'max_speed', type = 'usize', copy = true },
    { name = 'redline_speed', type = 'usize', copy = true },
    { name = 'engine_health', type = 'HitPoints', copy = true },
    { name = 'steering', type = 'SteerDirection', copy = true },
    { name = 'tyre_health', type = 'HitPoints', copy = true },
    { name = 'armour', type = 'usize', copy = true },
    { name = 'facing', type = 'Direction', copy = true },
    { name = 'bump_attacker', type = 'usize', copy = true },
    { name = 'projectile_damage', type = 'usize', copy = true },
    { name = 'hit_points', type = 'HitPoints', copy = true },
    { name = 'realtime_moves_remaining', type = 'usize', copy = true },
    { name = 'tile', type = 'TileType', copy = true },
    { name = 'position', type = 'Coord', copy = true },
    { name = 'opacity', type = 'f64', copy = true },
    { name = 'vision_distance', type = 'usize', copy = true },
    { name = 'inventory_capacity', type = 'usize', copy = true },
    { name = 'tile_depth', type = 'isize', copy = true },
    { name = 'name', type = 'NameMessageType', copy = true },
    { name = 'description', type = 'DescriptionMessageType', copy = true },
    { name = 'behaviour_type', type = 'BehaviourType', copy = true },
    { name = 'turn_offset', type = 'u64', copy = true },
    { name = 'turn_time', type = 'u64', copy = true },
    { name = 'shadow_entity', type = 'EntityId', copy = true },
    { name = 'schedule_ticket', type = 'ScheduleTicket', copy = true },
    { name = 'level_switch', type = 'LevelSwitch', copy = true },
    { name = 'level_switch_group', type = 'usize', copy = true },
    { name = 'probabilistic_animation', type = 'FirstWeightedProbabilisticChoice<TileType>' },
    { name = 'realtime_velocity', type = 'RealtimeVelocity' },
    { name = 'behaviour_state', type = 'BehaviourState' },
]

cells = [
    { name = 'message_log', type = 'MessageLog' },
    { name = 'drawable_knowledge', type = 'DrawableKnowledge' },
    { name = 'simple_npc_knowledge', type = 'SimpleNpcKnowledge' },
    { name = 'path_traverse', type = 'PathTraverse' },
    { name = 'inventory', type = 'EntitySet' },
    { name = 'weapon_slots', type = 'DirectionTable<EntityId>' },
]

action_flags = [
    { name = 'no_commit' },
    { name = 'player_died' },
    { name = 'physics' },
    { name = 'realtime_delay' },
    { name = 'start_realtime_move' },
]

action_data = [
    { name = 'then', type = "Reaction", copy = true },
    { name = 'alternative_turn_time', type = "u64", copy = true },
    { name = 'action_time_ms', type = "u64", copy = true },
    { name = 'level_switch_action', type = "LevelSwitchAction", copy = true },
    { name = 'try_level_switch', type = "EntityId", copy = true },
    { name = 'projectile_collision', type = "ProjectileCollision", copy = true },
    { name = 'schedule_invalidate', type = "ScheduleTicket", copy = true },
    { name = 'action_description', type = 'ActionDescription' },
]
